### ISSUE TITLE
[Dotazy] Vyjasnit následující

### ISSUE THREAD

**Issue by turonjan** [dynacase/demo-editor#13]
1. Ve kterých diagramech nechat uživatele editovat zalomení hran?
2. Ve kterých diagramech používat pravoúhlé zalamování?
3. Role/swimliny v PSD:
 * Umožnit editovat role (jsem spíše proti)
   * Varianta (A) - Editace názvu a id? 
    * Varianta (B) - Možnost vybrat jinou roli?
 * Umožnit přidávat/odebírat role? (jsem určitě proti - přílišná volnost uživatele - náročná implementace)

**Comment by turonjan** [comment]
1. OCD, PSD (NiceToHave), OFD
2. Přepínací, nebo klasické 
3. Varianta B

**Comment by turonjan** [comment]
3. Implementovat kontrolu - jedna role nemůže vystupovat jako executor pro více transakcí

**Comment by perglr** [comment]
Just the atomic one, the composed can.
